# Generated by Django 2.0 on 2019-05-13 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('management', models.CharField(max_length=10, verbose_name='负责人')),
                ('desc', models.TextField(max_length=200, verbose_name='描述')),
                ('addtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '网格区域',
                'verbose_name_plural': '网格区域',
            },
        ),
    ]
